### ISSUE TITLE
Improve watchlist

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#10]
User should be able to categorize it's watchlist in three section: finished, watching and aim to see. You could add these kind of buttons:

![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/2dc89f83-744c-44df-bb80-67c708ab006c)

**Comment by JurajVetrak** [comment]
Hello, do you need to just add that 3 button or also make logic for them and some buttons like add to {name of list (aim to see)}?
and also filters to show just shows from this list ?
If you need also this other things you can assign it to me :)

**Comment by Peacexoom** [comment]
We also need logic

**Comment by JurajVetrak** [comment]
okey nice :) can you please assign me to this ? I can do it

**Comment by Peacexoom** [comment]
Yeah sure @JurajVetrak

**Comment by JurajVetrak** [comment]
thank you :)

**Comment by JurajVetrak** [comment]
#28
