### ISSUE TITLE
Make anime detail page responsive

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#17]
![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/08b918b5-bce2-40a0-9ea6-3588b8860112)

**Comment by Cstrp** [comment]
okay, i can do it :) assign to me

**Comment by moonpatel** [comment]
Go on, @Cstrp

**Comment by Cstrp** [comment]
#18 @moonpatel or @Peacexoom idk, i'm sorry :)
