### ISSUE TITLE
Improve UI of signup/login page

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#2]

**Comment by AviGawande** [comment]
@Peacexoom  would you assign me the project to work on .

**Comment by Peacexoom** [comment]
> @Peacexoom would you assign me the project to work on .

@AviGawande Go on

**Comment by hardy07** [comment]
can you assign me, i can work on it?

**Comment by Peacexoom** [comment]
> can you assign me, i can work on it?

Hey, @hardy07 one person is already working on this issue. if he doesn't complete in next 2 days then i will assign you this issue. You can check other issues and if you find any other bug or want to add a feature in the website you can create your own issue and work on that till then.

**Comment by hardy07** [comment]
okay, sure @Peacexoom

**Comment by Peacexoom** [comment]
@hardy07 Go on

**Comment by hardy07** [comment]
okay, I started working on it

**Comment by hardy07** [comment]
@Peacexoom i made a pull request #19 Can you review and merge it?

**Comment by hardy07** [comment]
#19
