### ISSUE TITLE
Using Relative paths

### ISSUE THREAD

**Issue by BharatSharma29** [Peacexoom/AnimeHub#22]
I see you're using absolute path inside <Route>. Using relative path will be better has the app expands it's easier to maintain

**Comment by BharatSharma29** [comment]
Assign me this under hacktoberfest

**Comment by moonpatel** [comment]
> I see you're using absolute path inside . Using relative path will be better has the app expands it's easier to maintain

Can you show me where the absolute paths are used?

**Comment by BharatSharma29** [comment]
Inside the Route component in Front end folder

**Comment by moonpatel** [comment]
I dont think so we need any relative paths in App.jsx if you are talking about that. Can you pinpoint the file name if thats not the case ? @BharatSharma29

**Comment by BharatSharma29** [comment]
Well with relative paths it becomes easy to expand the app since as the application grows more ids will be added and every time you have to write the absolute path this makes it tedious. While using relative paths makes the code scalable.

**Comment by Peacexoom** [comment]
Ok @BharatSharma29 I am assigning this issue to you but do not guarantee that we will accept the pull request. If possible whatever changes you make, elaborate that how that change is making the app more scalable. Will that be ok?

**Comment by BharatSharma29** [comment]
Alright I'll explain it to you
