### ISSUE TITLE
Password hashing

### ISSUE THREAD

**Issue by IrfanSalim** [Peacexoom/AnimeHub#25]
Currently, the user's passwords are being stored in the DB as strings which is not a good practice considering security reasons.

We can hash the password and then store the hash in the DB.

Please assign this issue to me under Hacktoberfest, I would like to work on this.

**Comment by IrfanSalim** [comment]
@Peacexoom

**Comment by moonpatel** [comment]
Sure go ahead @IrfanSalim. I am assigning it to you. And use bcrypt for hashing.
