### ISSUE TITLE
Add top rated,  newest, movies, favorites section to navbar for mobile screen

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#3]
Desktop view:
![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/12696463-5f8b-4cee-b4fe-eeb9525226ab)

Mobile view:
![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/f80b0b60-ec7d-4132-af0c-f3280f8b88ca)

**Comment by TohDeKai** [comment]
Hi, I would like to work on this. Would you kindly assign it to me? thanks

**Comment by Peacexoom** [comment]
> Hi, I would like to work on this. Would you kindly assign it to me? thanks

Go ahead @TohDeKai

**Comment by SaahilShaikh17** [comment]
Hi I am interested in working on this as well , could i be assigned on this too?

**Comment by Peacexoom** [comment]
Sorry but this issue has already been solved. We are closing this issue. https://github.com/Peacexoom/AnimeHub/pull/21
