### ISSUE TITLE
anime name not readable on anime card

### ISSUE THREAD

**Issue by moonpatel** [Peacexoom/AnimeHub#30]
The anime name is not readable beacuase of its font color. Add a black gradient at the bottom of the anime card to make the text readable.

![image](https://github.com/Peacexoom/AnimeHub/assets/95487062/6e5e6e51-b793-417f-8428-e9a644545887)

**Comment by beatrizsmerino** [comment]
Hello [Peacexoom](https://github.com/Peacexoom)!! 😃
I want to do this task, could you please assign it to me?

**Comment by beatrizsmerino** [comment]
I am trying to do step 6 and 7 to contribute to the repository.
But I am unable to import the database or connect to the server.
Can you help me?

## 6. Import anime_hub database into MySQL Workbench
```
Open MySQL Workbench
Open the Local instance
Click Server->Data Import
Select Import from Self-Contained File option
Open AnimeHub\BackEnd\anime_hub_dump.sql
Press start import
```

What data should I set when creating the Local instance?
I am using Mamp Pro to start the server
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/658091d0-2ae0-4af0-a551-5041f76a47fa)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/714e5dfb-933c-49fd-9d3d-caef4ee4cff8)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/c0cdecc8-f181-4307-bc9e-d3abb4c15e54)


## 7. Make .env file in .\AnimeHub\BackEnd just like .env.example and add your password.

fill in the data of the env file
file by adding a password to `DB_PASSWORD` that must match the workbench password.
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/e290d3e7-04f4-48c2-9a55-bfd1bb26441c)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/897bd975-84ad-4f90-9b54-b41a449bec16)

![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/98c68f9e-3d40-4c91-a650-deab55e27f02)

![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/01ebca6b-3594-42b4-b1f9-2beae6813b66)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/c1ac8e23-fc46-4e2f-b054-cbf5d8137e47)

**Comment by beatrizsmerino** [comment]
It seems I had to activate this checkbox `Allow network access to MySQL`

![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/e6850f26-8c9f-4f7a-b735-e9bcff80a921)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/355eaba0-136e-433c-a4f8-b5273ed71d1f)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/2143eaba-ae72-4071-b06d-9fee63929221)
![image](https://github.com/Peacexoom/AnimeHub/assets/14045148/f3cfa8e6-758f-4382-8975-a737fb12d22a)

**Comment by mananbhimjiyani** [comment]
Hello, I wannaa do this task, can you assign it to me?

**Comment by moonpatel** [comment]
> Hello, I wannaa do this task, can you assign it to me?

@mananbhimjiyani you can look for any other issue because @beatrizsmerino asked first for assignment

**Comment by m-oswal** [comment]
hello, i have already solved the issue. let me create a pull request.

**Comment by m-oswal** [comment]
Hello, please check my pull request
