### ISSUE TITLE
refactor code in server.js

### ISSUE THREAD

**Issue by moonpatel** [Peacexoom/AnimeHub#37]
All the router are implemented in server.js which makes the app clunky. Create a seperate routes directory to make the code more organized.

**Comment by marinoffDev** [comment]
hey :) 
could you assign this to me?

**Comment by bhishekprajapati** [comment]
Hey @moonpatel I'd like to contribute!

**Comment by moonpatel** [comment]
Go on @bhishekprajapati !

**Comment by bhishekprajapati** [comment]
Hey @moonpatel I've created a PR.

Also add `hacktoberfest-accepted` label before the merge
