### ISSUE TITLE
Make anime card properly responsive

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#4]
![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/cac6a05c-3c8e-4d07-a515-39fda87ff3f6)

**Comment by DarkSoul26** [comment]
@Peacexoom let me take a look into this, please assign it to me

**Comment by Peacexoom** [comment]
> @Peacexoom let me take a look into this, please assign it to me

Go on @DarkSoul26

**Comment by DarkSoul26** [comment]
@Peacexoom please check #7
