### ISSUE TITLE
Make proper Alignment 

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#41]
This looks a little weird buttons spreading like this. Also make genre buttons in this section just like in the main genre page(a little bit heightened and add hover effect)
![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/0242478a-ee3f-4570-80bb-b1beb2fdb8ba)

**Comment by Pafestivo** [comment]
I can take this issue

**Comment by moonpatel** [comment]
> I can take this issue

Sure go ahead @Pafestivo
