### ISSUE TITLE
Misinformative error message on registration

### ISSUE THREAD

**Issue by Pafestivo** [Peacexoom/AnimeHub#43]
the password field doesn't seem to accept symbols - but it gives the error of `Must contain at least one capital letter, small letter and a digit`
kept me confused for a bit but then i realized the issue was that i had `!` in my password, so the verification proccess need a small adjustment - either modify the message that symbols are not allowed, or allow symbols.

**Comment by Pafestivo** [comment]
I'm currently assigned to another issue but I'll be able to take this issue once I'm done if no one took it by then.

**Comment by Rockleemode** [comment]
@Pafestivo can I work on the task if you're still busy?

**Comment by Pafestivo** [comment]
i'm done with the previous issue, but if you wanna do this one it's fine by me. 
I'd suggest adding support for symbols rather than modifying the error message, to allow people making strong passwords
i'm not a maintainer though so you'll have to wait for someone else to do the assigning.

**Comment by moonpatel** [comment]
> @Pafestivo can I work on the task if you're still busy?

Sure @Rockleemode you can work on this and add support for symbols instead of modifying error message as mentioned by @Pafestivo
