### ISSUE TITLE
Improvements for login and signup screens

### ISSUE THREAD

**Issue by Pafestivo** [Peacexoom/AnimeHub#47]
I'd suggest changing 'submit' on the register screen to 'register, and Also swap the places of the login and submit to be more intuitive - "continue the same path" should be on the right and "go back/do something else" should be on the left. (Same goes for the login screen)
I already have it done on my branch, you can just assign me the issue if you agree and I'll put up a PR

**Comment by Peacexoom** [comment]
ok go ahead @Pafestivo
