### ISSUE TITLE
Enhance Error Handling in app.js for Node.js Server

### ISSUE THREAD

**Issue by manojna191** [Peacexoom/AnimeHub#60]
**Description:** Introduce code in `app.js` to robustly handle unhandled promise rejections, uncaught exceptions, and unhandled routes.

**Is your feature request related to a problem? Please describe.**
In our Node.js server, we've identified instances of unhandled promise rejections, uncaught exceptions, and requests to unhandled routes. These pitfalls can compromise the server's reliability and security. By addressing these directly in `app.js`, we aim to reinforce our server's resilience.

**Describe the solution you'd like**
In the `app.js`:

1. **Unhandled Promise Rejections**: 
   - **Explanation**: When we have an error in the .env file then we may encounter the unhandled promise rejection error.
   - **Solution**: Prevent the server crash by closing the server gracefully
   
2. **Uncaught Exceptions**: 
   - **Explanation**: Exceptions that aren't caught in try-catch blocks might crash the server.
   - **Example**: Imagine having a console.log(abfgvhgvd)
   - **Solution**: Integrate a handler in `app.js` to log it and close the server gracefully

3. **Unhandled Routes**: 
   - **Explanation**: Requests to undefined routes can leak information or confuse users.
   - **Example**: A user who entered wrong route like localhost:3000/api/contests/random-msg 
   - **Solution**: Set up a final route handler to return a standardized 404 Not Found response and inform the user about checking the route

**Describe alternatives you've considered**
- For unhandled promise rejections and exceptions, we could use real-time error monitoring tools like Sentry for immediate alerts.
- For unhandled routes, establishing an analytics tool could give insights into frequent unrecognized route requests, helping to understand user patterns or detect malicious actors.

**Additional context**
Embedding these error-handling measures into our primary server file, `app.js`, is crucial for a robust server environment. It aids in preemptively addressing common pitfalls, ensuring a smoother user experience and providing developers with valuable error context.

**Comment by Peacexoom** [comment]
Nicely pointed out the issue @manojna191. Do you want to take this issue?

**Comment by Peacexoom** [comment]
Nicely pointed out the issue @manojna191. Do you want to take this issue?

**Comment by manojna191** [comment]
Yeah. I want to take this issue

**Comment by Peacexoom** [comment]
Go ahead @manojna191

**Comment by manojna191** [comment]
#61 
I have created the pull request with the promised changes 🙂.
