### ISSUE TITLE
Add email verification during creating a new account.

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#8]
If a new user create an account for the first time, a link should be sent in the email. And only after clicking on the link and verifying their email, user can move forward.

**Comment by IrfanSalim** [comment]
can you elaborate what kind of verification?

**Comment by Peacexoom** [comment]
> can you elaborate what kind of verification?

I have added the description.

**Comment by IrfanSalim** [comment]
It seems like a good opportunity to learn something new, I would like to work on this however the PR might take some time.

I might raise it over the weekend, if that's fine please assign it.

**Comment by Peacexoom** [comment]
> It seems like a good opportunity to learn something new, I would like to work on this however the PR might take some time.
> 
> I might raise it over the weekend, if that's fine please assign it.

Yeah no problem. You could explore the package nodemailer for this maybe.

**Comment by IrfanSalim** [comment]
> > It seems like a good opportunity to learn something new, I would like to work on this however the PR might take some time.
> > I might raise it over the weekend, if that's fine please assign it.
> 
> Yeah no problem. You could explore the package nodemailer for this maybe.

Yes I was thinking the same, cool thank you

**Comment by Reechychukz** [comment]
Hi, this is assigned already right?

**Comment by Peacexoom** [comment]
Yess
