### ISSUE TITLE
Images in animecard

### ISSUE THREAD

**Issue by Peacexoom** [Peacexoom/AnimeHub#9]
Images in animecard are not proper and also improve the animation when we hover on an animecard(maybe add time duration)

![image](https://github.com/Peacexoom/AnimeHub/assets/104450933/03dfd109-23e8-409e-8a62-c53d303a7142)

**Comment by TohDeKai** [comment]
Hello, I would like to be assigned this. Thanks!

**Comment by DanFogelberg** [comment]
Hi! I think I could fix this pretty well and that it would be good practice and fun!

**Comment by Peacexoom** [comment]
Go ahead @DanFogelberg

**Comment by PrathameshTheurkar** [comment]
hey I am pretty well familiar with ReactJs and I can fix this issue .  Can you assign this issue to me plz.

**Comment by Peacexoom** [comment]
Hey, @PrathameshTheurkar  one person is already working on this issue. if he doesn't complete in next 2 days then i will assign you this issue. If you find any other bug or want to add a feature in the website you can create your own issue and work on that till then.
